/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF, Text } from '@react-three/drei'


function Button(props) {
    const group = useRef();
    return (
        <group ref={group} {...props} dispose={null} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[-15517.6, 6673.5, -200]}>
                <mesh material={props.materials['.3_0']} geometry={props.nodes['������_2_������3_0'].geometry} />
                <mesh material={props.materials['.3_0']} geometry={props.nodes['������_������3_0001'].geometry} />
                <mesh material={props.materials['.3_0']} geometry={props.nodes['������_1_������3_0001'].geometry} />
                <mesh material={props.materials['.3_0']} geometry={props.nodes['������_������3_0'].geometry} />
            </group>
        </group>
    )
};

export default function Model(props) {
    const group = useRef()
    const { nodes, materials } = useGLTF('/models/hud.glb');

    return (
        <group ref={group} {...props} dispose={null}>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={[0.001, 0.001, 0.001]}>
                <Button nodes={nodes} materials={materials} />
                <group position={[0, 0, 0]} rotation={[0, 0, 0]}>
                    <group rotation={[Math.PI / 2, 0, 0]}>
                        <group position={[0, 0, -3000]} rotation={[-Math.PI, 0, 0]}>
                            <mesh
                                material={materials.material_13}
                                geometry={nodes['���������_2_������5_0'].geometry}
                                layers={1}
                            />
                        </group>
                        <group position={[0, 9600, 0]} >
                            <mesh 
                                material={materials.material_7} 
                                geometry={nodes['������������_������1_0'].geometry}
                            />
                        </group>
                        <group position={[0, 0, 0]}>
                            <mesh material={materials.material_9} geometry={nodes['���������_������_0'].geometry} />
                        </group>
                    </group>
                </group>
            </group>
        </group>
    )
}

useGLTF.preload('/models/hud.glb')
