/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Bansheeva (https://sketchfab.com/Bansheeva)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/lanterns-lowpoly-models-homework-11-e7d36f6ce9824228b787204591f6f356
title: Lanterns lowpoly models homework 11
*/

import React, { useRef } from 'react'
import { useFrame, useThree } from 'react-three-fiber'
import { useGLTF, Torus } from '@react-three/drei'
import { MeshLambertMaterial } from 'three'

export default function Model({ x, y, z }) {
    const group = useRef()
    const { nodes, materials } = useGLTF('/models/lantern.glb')

    useFrame((state) => {
        const time = state.clock.getElapsedTime();
        group.current.rotation.y = group.current.rotation.y + 0.01;
        group.current.position.y = group.current.position.y + Math.sin(time)/30;
    })

    return (
        <group ref={group} dispose={null} position={[x, y , z]}>
            <pointLight 
                distance={1000} 
                intensity={1} 
                color="cyan"
                layers={1}
            />
            <Torus
                position={[0, 0.5, 0]}
                scale={[0.5,0.5,0.5]}
                rotation ={[Math.PI/2, 0,0]}
                layers={1}
            >
                <meshLambertMaterial
                    color="cyan"
                    emissive="cyan"
                    attach="material" 
                />
            </Torus>
            <mesh
                material={materials.paper}
                geometry={nodes.JapaneseLantern_paper_0.geometry}
                position={[0, 0.66, 0]}
                layers={1}
            />
            <mesh
                material={materials.goldenrope}
                geometry={nodes.JapaneseLantern_goldenrope_0.geometry}
                position={[0, 1.35, 0]}
            />
            <mesh
                material={materials.redrope}
                geometry={nodes.JapaneseLantern_redrope_0.geometry}
                position={[0, 1.28, 0]}
            />
            <mesh
                material={materials.lambert1}
                geometry={nodes.JapaneseLantern_lambert1_0.geometry}
                position={[0, 1.49, 0]}
            />
            <mesh
                material={materials.wood}
                geometry={nodes.JapaneseLantern_wood_0.geometry}
                position={[0, 0.84, 0]} 
            />
        </group>
    )
}

useGLTF.preload('/models/lantern.glb')
